spring:
  security:
    oauth2:
      client:
        registration:
          google-login:
            provider: google
            client-id: 954024777360-lju1esfmeo6vuovpfv03604vs600uc1i.apps.googleusercontent.com
            client-secret: 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
  datasource:
    url: jdbc:postgresql://localhost:5432/stockwise
    username: postgres
    password: Postgres@123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: refresh

access:
  token:
    expiry:
      in:
        ms: 7200000
        
refresh:
  token:
    expiry:
      in:
        ms: 86400000

# Secrets Manager
secrets.manager:
  secret:
    id: stockwise-secrets
  region: ap-south-1